allowBuilds:
  "@prisma/engines": true
  msw: false
  prisma: true
  sharp: false
  unrs-resolver: false
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
onlyBuiltDependencies:
  - "@prisma/engines@7.8.0"
  - "msw@2.13.6"
  - prisma
overrides:
  "kysely": "0.28.17"
